//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_IvaKordic
{
    using System;
    using System.Collections.Generic;
    
    public partial class dijete
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dijete()
        {
            this.mjere_ploda = new HashSet<mjere_ploda>();
        }
    
        public int id { get; set; }
        public string spol { get; set; }
        public string prezime { get; set; }
        public string ime_oca { get; set; }
        public int majka_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mjere_ploda> mjere_ploda { get; set; }
        public virtual pacijent pacijent { get; set; }
    }
}
