//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_IvaKordic
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnevnik
    {
        public int id { get; set; }
        public string opis { get; set; }
        public string naslov { get; set; }
        public System.DateTime datum { get; set; }
        public int majka_id { get; set; }
    
        public virtual pacijent pacijent { get; set; }
    }
}
