//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_IvaKordic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class projekt_tbpEntities : DbContext
    {
        public projekt_tbpEntities()
            : base("name=projekt_tbpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dijete> dijete { get; set; }
        public virtual DbSet<dnevnik> dnevnik { get; set; }
        public virtual DbSet<doktor> doktor { get; set; }
        public virtual DbSet<doktor_pacijent> doktor_pacijent { get; set; }
        public virtual DbSet<kilaza> kilaza { get; set; }
        public virtual DbSet<mjere_ploda> mjere_ploda { get; set; }
        public virtual DbSet<opseg> opseg { get; set; }
        public virtual DbSet<pacijent> pacijent { get; set; }
        public virtual DbSet<pregled> pregled { get; set; }
        public virtual DbSet<tromjesjecje> tromjesjecje { get; set; }
    }
}
