//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_IvaKordic
{
    using System;
    using System.Collections.Generic;
    
    public partial class pacijent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pacijent()
        {
            this.dijete = new HashSet<dijete>();
            this.dnevnik = new HashSet<dnevnik>();
            this.doktor_pacijent = new HashSet<doktor_pacijent>();
            this.kilaza1 = new HashSet<kilaza>();
            this.opseg = new HashSet<opseg>();
            this.tromjesjecje = new HashSet<tromjesjecje>();
            this.pregled = new HashSet<pregled>();
        }
    
        public int id { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public System.DateTime datum_rodenja { get; set; }
        public string oib { get; set; }
        public Nullable<System.DateTime> datum_zaceca { get; set; }
        public float kilaza { get; set; }
        public string telefon { get; set; }
        public string adresa { get; set; }
        public int uloga { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dijete> dijete { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dnevnik> dnevnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doktor_pacijent> doktor_pacijent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kilaza> kilaza1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<opseg> opseg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tromjesjecje> tromjesjecje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pregled> pregled { get; set; }
    }
}
